export const TOOL_CARDS = [
  {
    key: 'mortgage',
    icon: 'calculator-outline' as const,
    titleKey: 'tools.mortgage.title',
    descKey: 'tools.mortgage.description',
    route: '/(tabs)/tools/mortgage' as const,
    imageUri: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=85',
  },
  {
    key: 'rentVsBuy',
    icon: 'home-outline' as const,
    titleKey: 'tools.rentVsBuy.title',
    descKey: 'tools.rentVsBuy.description',
    route: '/(tabs)/tools/rent-vs-buy' as const,
    imageUri: 'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&q=85',
  },
  {
    key: 'affordability',
    icon: 'wallet-outline' as const,
    titleKey: 'tools.affordability.title',
    descKey: 'tools.affordability.description',
    route: '/(tabs)/tools/affordability' as const,
    imageUri: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=85',
  },
  {
    key: 'movingCosts',
    icon: 'cube-outline' as const,
    titleKey: 'tools.movingCosts.title',
    descKey: 'tools.movingCosts.description',
    route: '/(tabs)/tools/moving-costs' as const,
    imageUri: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=800&q=85',
  },
  {
    key: 'renovation',
    icon: 'hammer-outline' as const,
    titleKey: 'tools.renovation.title',
    descKey: 'tools.renovation.description',
    route: '/(tabs)/tools/renovation' as const,
    imageUri: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=85',
  },
  {
    key: 'districtComparison',
    icon: 'bar-chart-outline' as const,
    titleKey: 'tools.districtComparison.title',
    descKey: 'tools.districtComparison.description',
    route: '/(tabs)/tools/district-comparison' as const,
    imageUri: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&q=85',
  },
  {
    key: 'currencyHistory',
    icon: 'trending-up-outline' as const,
    titleKey: 'tools.currencyHistory.title',
    descKey: 'tools.currencyHistory.description',
    route: '/(tabs)/tools/currency-history' as const,
    imageUri: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=85',
  },
] as const;
